export const ritualDetailsData = {
 "Andhra Pradesh": {
  "Mangala Snanam": {
    description: "Holy bath ritual for bride and groom before marriage",
    history: "Ancient ritual practiced for over 2000 years in Andhra Pradesh, rooted in Hindu customs where water purification is considered essential before marriage ceremonies.",
    significance: "Represents spiritual cleansing, removal of negative energy, and preparation for the sacred union of marriage.",
    process: [
      "Bride and groom take separate ritual baths",
      "Holy water mixed with turmeric and sandalwood",
      "Family members apply fragrances and oils",
      "New clothes are worn after the bath",
      "Prayers are recited for blessings",
    ],
    culturalImportance: "Central to Telugu marriage traditions, symbolizing purity and readiness for married life.",
    region: "Telangana, Andhra Pradesh",
    duration: "30-45 minutes per person",
    participants: "Bride, Groom, Close family members",
    offerings: "Flowers, turmeric, sandalwood, fragrant oils, water",
    bestTime: "Early morning before marriage ceremony",
    videos: "Mangala Snanam Telugu Wedding Ritual",
  },
  "Muggu Drawing": {
    description: "Traditional rangoli made with rice flour at doorsteps",
    history: "Ancient South Indian tradition dating back 5000+ years, mentioned in Vedic texts as a form of artistic and spiritual expression.",
    significance: "Represents prosperity, welcomes divine blessings, and is a form of meditation and daily prayer.",
    process: [
      "Women wake early and clean the doorstep",
      "Mix rice flour with water to create paste",
      "Draw geometric and floral patterns",
      "Use fingers or special tools for intricate designs",
      "Completed before sunrise",
    ],
    culturalImportance: "UNESCO-recognized art form, preserves family traditions, women-centric ritual.",
    region: "South India - Telangana, Andhra Pradesh, Tamil Nadu",
    duration: "30-60 minutes",
    participants: "Women of the household",
    offerings: "Rice flour, turmeric, colored powders, water",
    bestTime: "Early morning (4-6 AM)",
    videos: "Muggu Kolam Drawing Andhra Pradesh Art",
  },
  "Pelli Chupulu": {
    description: "Bride-giving ceremony central to Telugu weddings",
    history: "Ancient custom from Hindu scriptures (Manusmriti), symbolizing the sacred act of father giving daughter to groom.",
    significance: "Represents family bonding, trust, and the beginning of a new chapter in bride's life.",
    process: [
      "Bride's father presents daughter to groom",
      "Exchange of vows and rings",
      "Application of vermilion (sindoor)",
      "Tying of mangalsutra",
      "Blessing from elders",
    ],
    culturalImportance: "Core ritual in Telugu marriages, establishes legal and social status of marriage.",
    region: "Andhra Pradesh, Telangana, Karnataka",
    duration: "20-30 minutes",
    participants: "Bride, Groom, Bride's parents, Priest, Elders",
    offerings: "Flowers, coconut, banana leaves, sweets",
    bestTime: "During marriage ceremony (auspicious time)",
    videos: "Pelli Chupulu Telugu Marriage Ceremony",
  },
  "Talambralu Exchange": {
    description: "Exchange of rice and jaggery between bride and groom",
    history: "Ancient Telugu wedding ritual symbolizing sharing and commitment between spouses.",
    significance: "Represents the sweetness and nourishment of married life, mutual responsibility.",
    process: [
      "Bride and groom exchange talambralu (rice with jaggery)",
      "Each feeds the other",
      "Family members do the same",
      "Exchanged multiple times in ceremony",
      "Symbolizes feeding and caring for each other",
    ],
    culturalImportance: "Beautiful ritual showing commitment to nourish and care for spouse.",
    region: "Andhra Pradesh, Telangana",
    duration: "15-20 minutes",
    participants: "Bride, Groom, Family members",
    offerings: "Rice, jaggery, flowers",
    bestTime: "During wedding ceremony",
    videos: "Talambralu Exchange Telugu Wedding Ritual",
  },
  "Saptapadi": {
    description: "Seven sacred steps taken together by bride and groom",
    history: "Vedic ritual mentioned in ancient Hindu texts, represents journey through marriage.",
    significance: "Each step symbolizes different aspects of married life - nourishment, health, wealth, happiness, progeny, health, and lifelong friendship.",
    process: [
      "Bride and groom stand together",
      "Priest chants sacred mantras",
      "Couple takes seven steps forward",
      "Each step has specific meaning",
      "Family witnesses the sacred journey",
    ],
    culturalImportance: "Most important ritual in Telugu marriages, binds couple together.",
    region: "Andhra Pradesh, Telangana, entire South India",
    duration: "10-15 minutes",
    participants: "Bride, Groom, Priest, Family",
    offerings: "Flowers, sacred materials, incense",
    bestTime: "Central part of marriage ceremony",
    videos: "Saptapadi Seven Steps Telugu Wedding",
  },
  "Oonjal Puja": {
    description: "Swinging of deity idols during festival celebrations",
    history: "Ancient Telugu tradition honoring gods during festivals, mentioned in temple records.",
    significance: "Celebrates divine presence, brings community together, ensures blessing for devotees.",
    process: [
      "Decorated swing (oonjal) prepared with flowers",
      "Deity idol placed gently",
      "Devotees swing in rhythmic motion",
      "Chanting of mantras and prayers",
      "Community participation with offerings",
    ],
    culturalImportance: "Important temple ritual during festivals, community bonding event.",
    region: "Andhra Pradesh, Telangana temples",
    duration: "1-2 hours",
    participants: "Priests, devotees, temple staff, community members",
    offerings: "Flowers, incense, sweets, prayers",
    bestTime: "Festival days and special occasions",
    videos: "Oonjal Puja Deity Swinging Festival Ritual",
  },
  "Bathukamma Celebration": {
    description: "Floral stacking ritual celebrated by women during monsoon",
    history: "Ancient Telangana ritual honoring Mother Earth during monsoon season.",
    significance: "Celebrates fertility, harvest, and thanksgiving for rains and prosperity.",
    process: [
      "Women gather colored flowers",
      "Stack flowers in spiral pattern",
      "Bathukamma (stacked flowers) is created",
      "Women sing traditional songs around it",
      "Immersed in water after celebration",
    ],
    culturalImportance: "Unique to Telangana, UNESCO-recognized festival, celebrates women and nature.",
    region: "Telangana, parts of Andhra Pradesh",
    duration: "2-3 hours celebration",
    participants: "Women of all ages, family members",
    offerings: "Colored flowers, rice, sugarcane",
    bestTime: "Bathukamma season (September-October)",
    videos: "Bathukamma Flower Stacking Festival Telangana",
  },
  "Toli Janmashtami": {
    description: "Hanging of dolls and figurines during Krishna's birth celebration",
    history: "Ancient tradition of arranging deity dolls, part of Andhra Pradesh home culture.",
    significance: "Celebrates Krishna's birth, invites his blessings into homes.",
    process: [
      "Dolls and figurines arranged in steps/platforms",
      "Krishna and Radha idols central",
      "Decorated with flowers and lights",
      "Prayers and songs performed",
      "Friends and family visit to view arrangement",
    ],
    culturalImportance: "Important home ritual during Janmashtami, showcases creativity and devotion.",
    region: "Andhra Pradesh, Telangana",
    duration: "Setup 2-3 hours, display several days",
    participants: "Women and children of household",
    offerings: "Dolls, flowers, sweets, lights",
    bestTime: "Janmashtami festival (August-September)",
    videos: "Toli Janmashtami Doll Arrangement Ritual",
  },
  "Gannala Gaddi": {
    description: "Seating of bride on decorated wooden plank during wedding",
    history: "Ancient Telugu wedding ritual symbolizing bride's transition to married status.",
    significance: "Represents bride's elevation and readiness for married responsibilities.",
    process: [
      "Decorated wooden plank (gaddi) is prepared",
      "Bride sits on plank",
      "Covered with silk cloth",
      "Prayers and blessings given",
      "Groom joins bride",
    ],
    culturalImportance: "Important pre-marriage ritual in Telugu weddings.",
    region: "Andhra Pradesh, Telangana",
    duration: "20-30 minutes",
    participants: "Bride, Groom, Bride's family, Elders",
    offerings: "Wooden plank, flowers, silk cloth",
    bestTime: "Pre-wedding ceremony",
    videos: "Gannala Gaddi Telugu Wedding Ritual",
  },
  "Telanaga Puja": {
    description: "Ritual worship in temples with specific procedures and chants",
    history: "Ancient temple ritual procedure maintaining Vedic traditions.",
    significance: "Ensures proper worship, invokes divine blessings according to scriptures.",
    process: [
      "Priest performs ritual bathing of deity",
      "Application of sandalwood paste",
      "Offering of flowers and incense",
      "Chanting of Vedic mantras",
      "Distribution of blessed items to devotees",
    ],
    culturalImportance: "Maintains religious traditions, preserves Vedic knowledge.",
    region: "Andhra Pradesh temples",
    duration: "1-2 hours",
    participants: "Priest, devotees, temple staff",
    offerings: "Flowers, incense, sandalwood, sweets",
    bestTime: "Daily temple worship, special occasions",
    videos: "Telanaga Puja Temple Worship Ritual",
  },
  "Navratri Golu": {
    description: "Display of dolls during Navratri festival in steps",
    history: "Ancient tradition celebrating nine forms of goddess Durga.",
    significance: "Honors feminine divine power, celebrates good over evil.",
    process: [
      "Steps arranged in odd numbers (3, 5, 7, 9)",
      "Dolls placed from bottom to top",
      "Goddess Durga at top",
      "Decorated with flowers, lights, and colors",
      "Women visit homes singing traditional songs",
    ],
    culturalImportance: "Important home ritual during Navratri, maintains cultural tradition.",
    region: "Andhra Pradesh, Telangana, South India",
    duration: "Setup 2-3 hours, display 9 days",
    participants: "Women and children",
    offerings: "Dolls, flowers, incense, sweets",
    bestTime: "Navratri festival (September-October)",
    videos: "Navratri Golu Festival Display Ritual",
  },
},

  "Arunachal Pradesh": {
    "Tribal House Blessing": {
      description: "Sacred ritual with rice beer for blessing new homes",
      history: "Ancient tribal tradition practiced for centuries, part of indigenous belief systems honoring ancestors and spirits.",
      significance: "Seeks blessings from ancestors and protective spirits for prosperity and safety in new home.",
      process: [
        "Community gathers for blessing ceremony",
        "Rice beer (zu) is offered to spirits",
        "Elders perform chanting rituals",
        "Family members take blessings",
        "Sharing of food and drink",
      ],
      culturalImportance: "Integral to tribal identity, strengthens community bonds, honors ancestral traditions.",
      region: "Arunachal Pradesh tribal communities",
      duration: "2-3 hours",
      participants: "Family, tribe members, elders, shamans",
      offerings: "Rice beer, meat, traditional foods, flowers",
      bestTime: "Before entering new home",
      videos: "Arunachal Pradesh Tribal House Blessing Ritual",
    },
    "Apatani Tattooing": {
      description: "Traditional facial tattoo ritual indicating tribe and status",
      history: "Ancient Apatani tradition dating back centuries, part of ethnic identity and tribal classification system.",
      significance: "Marks tribal belonging, distinguishes clan identity, symbolizes courage and maturity.",
      process: [
        "Performed on young girls and boys",
        "Intricate patterns tattooed on face",
        "Using traditional tools and natural pigments",
        "Ceremonial celebration follows",
        "Recognition of tribal status",
      ],
      culturalImportance: "Unique to Apatani tribe, preserves ethnic identity, now practiced less frequently.",
      region: "Arunachal Pradesh - Apatani plateau",
      duration: "Several sessions over days",
      participants: "Young tribe members, tattoo artists, family",
      offerings: "Natural pigments, rice, meat",
      bestTime: "Coming of age ceremonies",
      videos: "Apatani Traditional Tattooing Ritual",
    },
  },
  "Assam": {
    "Gamosa Offering": {
      description: "Presenting traditional cotton scarf as symbol of respect",
      history: "Ancient Assamese custom of hospitality and respect, dating back centuries in Assam's cultural tradition.",
      significance: "Represents warmth, welcome, respect, and is offered at important occasions and meetings.",
      process: [
        "Gamosa is prepared from pure cotton",
        "Decorated with traditional patterns",
        "Presented with both hands as sign of respect",
        "Worn around neck or kept as memento",
        "Accepted with gratitude",
      ],
      culturalImportance: "Symbol of Assamese hospitality, awarded at official ceremonies, represents cultural identity.",
      region: "Assam, Northeast India",
      duration: "Few minutes for presentation",
      participants: "Host and guest",
      offerings: "Gamosa (traditional cotton scarf)",
      bestTime: "Welcoming guests, official meetings",
      videos: "Gamosa Assamese Traditional Offering",
    },
    "Mekhela Chador Weaving": {
      description: "Traditional handloom weaving of Assamese dress",
      history: "Ancient weaving tradition practiced for centuries, part of Assamese cultural heritage and women's craftsmanship.",
      significance: "Represents women's artistic skills, cultural preservation, and economic contribution.",
      process: [
        "Women prepare cotton or silk threads",
        "Set up traditional looms",
        "Weave intricate patterns by hand",
        "Takes weeks to complete one garment",
        "Natural dyes used for colors",
      ],
      culturalImportance: "Preserves traditional art form, supports women's livelihood, maintains cultural identity.",
      region: "Assam, Northeast India",
      duration: "Several weeks per garment",
      participants: "Women weavers, family members",
      offerings: "Cotton/silk threads, natural dyes, materials",
      bestTime: "Year-round practice",
      videos: "Mekhela Chador Weaving Assam Traditional",
    },
  },
  "Bihar": {
    "Suhag Rituals": {
      description: "Daily married women's rituals honoring marital status",
      history: "Ancient Hindu tradition documented in scriptures, represents married women's devotion to husbands.",
      significance: "Symbolizes marital commitment, longevity of marriage, and husband's wellbeing.",
      process: [
        "Application of vermilion (sindoor) daily",
        "Wearing bangles and jewelry",
        "Observing fasts for husband's health",
        "Evening prayers for family welfare",
        "Traditional ceremonies on auspicious days",
      ],
      culturalImportance: "Central to Bihar's matrimonial traditions, reflects women's religious devotion.",
      region: "Bihar, parts of North India",
      duration: "Daily practice throughout married life",
      participants: "Married women, family members",
      offerings: "Vermilion, bangles, flowers, foods",
      bestTime: "Daily morning and evening rituals",
      videos: "Suhag Rituals Bihar Tradition",
    },
    "Vivaha Mandap Ritual": {
      description: "Elaborate wedding pavilion decoration and ceremonies",
      history: "Traditional Bihar wedding practice with roots in Vedic marriage ceremonies.",
      significance: "Sacred space for marriage vows, decorated to invite divine blessings.",
      process: [
        "Construction of mandap with bamboo/wood",
        "Decoration with flowers and fabrics",
        "Placement of sacred objects",
        "Fire altar preparation",
        "Ritual purification of space",
      ],
      culturalImportance: "Essential component of Bihar weddings, creates sacred atmosphere.",
      region: "Bihar, North India",
      duration: "1-2 days for setup and ceremony",
      participants: "Bride, Groom, Priest, Family",
      offerings: "Flowers, fabrics, sacred materials",
      bestTime: "Wedding date",
      videos: "Bihar Wedding Mandap Ritual Setup",
    },
  },
  "Chhattisgarh": {
    "Ghotul Tradition": {
      description: "Youth learning center and social institution in tribal communities",
      history: "Ancient tribal system for educating youth, documented in tribal folklore for centuries.",
      significance: "Provides cultural education, social training, and prepares youth for community life.",
      process: [
        "Separate dormitory for unmarried youth",
        "Traditional skills taught by elders",
        "Community gatherings and celebrations",
        "Cultural performances and songs",
        "Preparation for marriage and adulthood",
      ],
      culturalImportance: "Unique tribal institution, preserves traditional knowledge, maintains social cohesion.",
      region: "Chhattisgarh tribal areas",
      duration: "Years of participation",
      participants: "Youth, elders, tribal leaders",
      offerings: "Food, materials for learning",
      bestTime: "Throughout year, festivals celebrated",
      videos: "Ghotul Tribal Youth Tradition Chhattisgarh",
    },
    "Mahua Offering": {
      description: "First rice brew offering to ancestors",
      history: "Ancient tribal ritual honoring ancestors and seeking their blessings for harvest.",
      significance: "Acknowledges debt to ancestors, ensures prosperity and protection.",
      process: [
        "Rice is fermented to create traditional brew",
        "First batch offered to ancestors",
        "Prayers and chanting performed",
        "Rest shared with community",
        "Festival celebrated around this ritual",
      ],
      culturalImportance: "Central to tribal seasonal celebrations, honors ancestral lineage.",
      region: "Chhattisgarh tribal communities",
      duration: "Few days for preparation",
      participants: "Family, tribe members, elders",
      offerings: "Rice, traditional ingredients, flowers",
      bestTime: "Harvest season",
      videos: "Mahua Offering Chhattisgarh Tribal Ritual",
    },
  },
  "Goa": {
    "Holy Water Blessing": {
      description: "Christian blessing ritual using blessed water in homes",
      history: "Portuguese-influenced Christian tradition practiced in Goa for centuries.",
      significance: "Seeks divine protection and blessings for household members.",
      process: [
        "Holy water is blessed by priest",
        "Applied to forehead of family members",
        "Rooms of house are sprinkled",
        "Prayers recited for protection",
        "Religious hymns sung",
      ],
      culturalImportance: "Part of Christian faith practice in Goa, reflects religious devotion.",
      region: "Goa",
      duration: "30-45 minutes",
      participants: "Family, priest",
      offerings: "Holy water, flowers, incense",
      bestTime: "Before major events or regularly",
      videos: "Goan Christian Holy Water Blessing",
    },
    "Coconut Bride Ritual": {
      description: "Bride blessed with coconut and rice during wedding",
      history: "Traditional Goan Christian wedding custom with ancient roots.",
      significance: "Symbolizes fertility, prosperity, and divine blessing on marriage.",
      process: [
        "Bride holds coconut during ceremony",
        "Rice grains sprinkled on bride",
        "Prayers for long marriage",
        "Blessings from elders",
        "Coconut distributed to guests",
      ],
      culturalImportance: "Unique to Goan Christian weddings, blends Hindu and Christian elements.",
      region: "Goa",
      duration: "15-20 minutes",
      participants: "Bride, Groom, Family, Priest",
      offerings: "Coconut, rice, flowers",
      bestTime: "Wedding ceremony",
      videos: "Goan Wedding Coconut Ritual Blessing",
    },
  },
  "Gujarat": {
    "Gol Dhana Engagement": {
      description: "Exchange of jaggery and coriander seeds during engagement",
      history: "Ancient Gujarati custom symbolizing sweetness and spice of relationship.",
      significance: "Represents the balanced nature of marriage - sweetness and variety.",
      process: [
        "Bride's family presents jaggery",
        "Groom's family presents coriander seeds",
        "Exchange done formally with blessings",
        "Distributed to guests",
        "Celebration with music and dance",
      ],
      culturalImportance: "Central to Gujarati engagements, unique tradition of the state.",
      region: "Gujarat",
      duration: "30 minutes to 1 hour",
      participants: "Both families, relatives",
      offerings: "Jaggery, coriander seeds, sweets",
      bestTime: "Engagement ceremony",
      videos: "Gujarati Gol Dhana Engagement Ritual",
    },
    "Matli Ritual": {
      description: "Bride's mother gifts pots to groom's family",
      history: "Ancient tradition indicating bride's household skills and mother's blessings.",
      significance: "Symbolizes mother's support, household prosperity, and care for daughter.",
      process: [
        "Bride's mother selects decorative pots",
        "Pots filled with sweets and gifts",
        "Presented to groom's family formally",
        "Accepted with blessings",
        "Kept as symbol of relationship",
      ],
      culturalImportance: "Important pre-wedding ritual in Gujarati weddings.",
      region: "Gujarat",
      duration: "1-2 hours",
      participants: "Both families, elders",
      offerings: "Decorative pots, sweets, gifts",
      bestTime: "Pre-wedding ceremonies",
      videos: "Gujarati Matli Ritual Pot Giving",
    },
  },
  "Haryana": {
    "Ghodi Baraat": {
      description: "Groom arrives on horse with traditional ceremonial procession",
      history: "Ancient tradition symbolizing groom's status and courage.",
      significance: "Displays groom's family pride and marks beginning of wedding celebration.",
      process: [
        "Groom dressed in traditional sherwani",
        "Rides decorated horse or vehicle",
        "Band plays traditional music",
        "Family and friends accompany",
        "Bride's family welcomes with honors",
      ],
      culturalImportance: "Central to Haryana weddings, showcase of community celebration.",
      region: "Haryana, North India",
      duration: "2-3 hours including procession",
      participants: "Groom, family, musicians, dancers",
      offerings: "Flowers, sweets, gifts for welcome",
      bestTime: "Evening before or morning of wedding",
      videos: "Haryana Ghodi Baraat Traditional Ceremony",
    },
    "Sehra Ritual": {
      description: "Decorative head covering for groom during wedding",
      history: "Traditional Haryana custom dating back centuries.",
      significance: "Protects groom during ceremony, symbolizes readiness for marriage.",
      process: [
        "Sehra made of flowers and gold",
        "Placed on groom's head",
        "Heavy with decorative elements",
        "Removed after first meeting with bride",
        "Replaced multiple times during ceremony",
      ],
      culturalImportance: "Iconic element of Haryana weddings, visible symbol of groom's status.",
      region: "Haryana, Punjab, North India",
      duration: "Throughout wedding ceremony",
      participants: "Groom, family members",
      offerings: "Flowers, gold, decorative materials",
      bestTime: "Wedding ceremony",
      videos: "Haryana Sehra Ritual Tradition",
    },
  },
  "Himachal Pradesh": {
    "Devta Tradition": {
      description: "Villagers carry local deity on palanquin for community blessings",
      history: "Ancient mountain tradition honoring local gods and community unity.",
      significance: "Seeks divine blessings for community welfare, prosperity, and protection.",
      process: [
        "Local deity idol placed on decorated palanquin",
        "Villagers take turns carrying it",
        "Procession through village",
        "Stops at homes for blessings",
        "Community prayers and offerings",
      ],
      culturalImportance: "Central to village life in Himachal, maintains spiritual connection.",
      region: "Himachal Pradesh",
      duration: "Several hours to full day",
      participants: "Entire village community",
      offerings: "Flowers, incense, food items",
      bestTime: "Religious festivals and special occasions",
      videos: "Himachal Pradesh Devta Palanquin Tradition",
    },
    "Kula Devta Ritual": {
      description: "Worship of family deity before important decisions",
      history: "Ancient tradition of honoring ancestral protective deities.",
      significance: "Seeks guidance and blessings from family protector deity.",
      process: [
        "Family gathers at sacred space",
        "Prayers offered to Kula Devta",
        "Offerings made - flowers, food",
        "Seeking blessings for decision",
        "Auspicious timing determined",
      ],
      culturalImportance: "Guides major life decisions, maintains spiritual family bonds.",
      region: "Himachal Pradesh mountain communities",
      duration: "1-2 hours",
      participants: "Family members, elder priest",
      offerings: "Flowers, fruits, sweets, incense",
      bestTime: "Before marriages, business ventures, travels",
      videos: "Kula Devta Ritual Himachal Pradesh",
    },
  },
  "Jharkhand": {
    "Sarhul Marriage Ritual": {
      description: "Sacred thread tying on trees during tribal weddings",
      history: "Ancient tribal ritual honoring nature and seeking blessings.",
      significance: "Connects marriage to nature, ensures fertility and prosperity.",
      process: [
        "Bride and groom visit sacred trees",
        "Tie sacred threads on branches",
        "Prayers to nature and ancestors",
        "Exchange of vows before trees",
        "Community witnesses ritual",
      ],
      culturalImportance: "Core tribal ritual, honors connection between marriage and nature.",
      region: "Jharkhand tribal areas",
      duration: "1-2 hours",
      participants: "Bride, Groom, Tribe members, Priest",
      offerings: "Sacred threads, flowers, natural items",
      bestTime: "During tribal marriage season",
      videos: "Sarhul Marriage Ritual Jharkhand Tribe",
    },
    "Akhra Fire Ritual": {
      description: "Family gathered around sacred fire for decision-making",
      history: "Ancient tribal ritual for community council and important decisions.",
      significance: "Seeks wisdom and guidance for collective decisions.",
      process: [
        "Sacred fire lit at community gathering",
        "Elders sit around fire",
        "Matters discussed and debated",
        "Decisions made collectively",
        "Offerings made to fire",
      ],
      culturalImportance: "Maintains tribal democracy and community governance.",
      region: "Jharkhand tribal communities",
      duration: "Several hours",
      participants: "Tribe members, elders, council",
      offerings: "Wood, grains, flowers",
      bestTime: "Important occasions requiring decisions",
      videos: "Jharkhand Akhra Fire Community Ritual",
    },
  },
  "Karnataka": {
    "Mangalorean Bride Ritual": {
      description: "Bride carries coconut to groom's home after marriage",
      history: "Traditional Mangalorean Catholic custom with ancient roots.",
      significance: "Brings prosperity and blessings to new household.",
      process: [
        "Bride holds fresh coconut after wedding",
        "Carries it to new home",
        "Breaks coconut at entrance",
        "Distributed to household members",
        "Symbolizes new beginning",
      ],
      culturalImportance: "Unique to Mangalorean communities, blends Catholic and local traditions.",
      region: "Karnataka - Mangalore region",
      duration: "Part of post-wedding ceremony",
      participants: "Bride, Groom, Family",
      offerings: "Coconut, flowers, sweets",
      bestTime: "After wedding ceremony",
      videos: "Mangalorean Bride Coconut Ritual Karnataka",
    },
    "Tulsi Puja": {
      description: "Daily worship of sacred Tulsi (basil) plant",
      history: "Ancient Hindu practice honoring Tulsi as manifestation of goddess.",
      significance: "Brings spiritual purity and prosperity to household.",
      process: [
        "Water given to Tulsi plant daily",
        "Flowers and incense offered",
        "Prayers recited morning and evening",
        "Family gathers for worship",
        "Leaves used for religious purposes",
      ],
      culturalImportance: "Maintains spiritual connection, part of daily household practice.",
      region: "Karnataka, across South India",
      duration: "10-15 minutes daily",
      participants: "Family members",
      offerings: "Water, flowers, incense",
      bestTime: "Morning and evening",
      videos: "Tulsi Puja Daily Worship Karnataka",
    },
  },
  "Kerala": {
    "Puthiyapla Tradition": {
      description: "Sharing sweets when bride enters groom's home",
      history: "Ancient Kerala custom celebrating new family member's arrival.",
      significance: "Represents sweetness of new relationships and acceptance.",
      process: [
        "Bride prepares or brings traditional sweets",
        "Distributed to family and neighbors",
        "Announced as official family member",
        "Celebration with music and dance",
        "Community blessing received",
      ],
      culturalImportance: "Marks bride's integration into family and society.",
      region: "Kerala",
      duration: "30 minutes to 1 hour",
      participants: "Bride, Groom's family, neighbors",
      offerings: "Traditional Kerala sweets, fruits",
      bestTime: "First day after marriage",
      videos: "Kerala Puthiyapla Bride Welcome Ritual",
    },
    "Kasavu Saree Wearing": {
      description: "Wearing traditional white saree with gold border",
      history: "Ancient Kerala tradition, part of cultural identity for centuries.",
      significance: "Represents purity, grace, and Keralite cultural pride.",
      process: [
        "Traditional Kasavu saree draped carefully",
        "Worn during important rituals",
        "Blessed by elders",
        "Accompanied by traditional jewelry",
        "Appropriate for ceremonial occasions",
      ],
      culturalImportance: "UNESCO-recognized textile, symbol of Kerala identity.",
      region: "Kerala",
      duration: "15-20 minutes for wearing",
      participants: "Women during rituals",
      offerings: "Traditional Kasavu saree, jewelry",
      bestTime: "During auspicious rituals and ceremonies",
      videos: "Kasavu Saree Wearing Kerala Tradition",
    },
  },
  "Madhya Pradesh": {
    "Laya Ceremony": {
      description: "Gond tribal ritual before wedding ceremonies",
      history: "Ancient tribal custom preparing bride and groom for marriage.",
      significance: "Spiritual and physical preparation for marital union.",
      process: [
        "Bride and groom purified with oils",
        "Traditional songs sung",
        "Elders bless the couple",
        "Community gathers for celebration",
        "Traditional feast prepared",
      ],
      culturalImportance: "Central to Gond tribal weddings, maintains cultural traditions.",
      region: "Madhya Pradesh tribal areas",
      duration: "1-2 days",
      participants: "Bride, Groom, Tribe members",
      offerings: "Oils, flowers, traditional foods",
      bestTime: "Before wedding ceremony",
      videos: "Gond Tribal Laya Wedding Ceremony",
    },
    "Narmada Snan": {
      description: "Sacred bath in Narmada river before major rituals",
      history: "Ancient Hindu tradition honoring sacred river.",
      significance: "Spiritual purification for important ceremonies.",
      process: [
        "Pilgrims travel to Narmada river",
        "Ritual bathing performed",
        "Prayers offered to river goddess",
        "Holy water collected",
        "Used for ceremonies",
      ],
      culturalImportance: "Honors sacred river, maintains spiritual purity.",
      region: "Madhya Pradesh - Narmada valley",
      duration: "2-3 hours for entire ritual",
      participants: "Family members, pilgrims",
      offerings: "Flowers, prayers, grains",
      bestTime: "Before important ceremonies",
      videos: "Narmada Snan Sacred Bath Ritual MP",
    },
  },
  "Maharashtra": {
    "Kelvan Ritual": {
      description: "Family blessings before wedding ceremony",
      history: "Traditional Marathi custom seeking family approval and blessings.",
      significance: "Family endorsement of marriage, ensures collective support.",
      process: [
        "Bride and groom presented to family",
        "Elders offer blessings",
        "Gifts exchanged",
        "Traditional songs sung",
        "Feast shared",
      ],
      culturalImportance: "Strengthens family bonds, crucial in Marathi weddings.",
      region: "Maharashtra",
      duration: "1-2 hours",
      participants: "Bride, Groom, Both families",
      offerings: "Gifts, sweets, flowers",
      bestTime: "Day before or morning of wedding",
      videos: "Marathi Kelvan Wedding Blessing Ritual",
    },
    "Sakharpuda Gift": {
      description: "Groom gifted sugar to symbolize sweetness",
      history: "Traditional Marathi custom with symbolic meaning.",
      significance: "Wishes for sweet married life and good relationship.",
      process: [
        "Sugar wrapped in cloth",
        "Presented to groom",
        "Accepted with blessings",
        "Distributed to guests",
        "Symbolizes sweetness of marriage",
      ],
      culturalImportance: "Unique Marathi tradition, adds sweetness to ceremony.",
      region: "Maharashtra",
      duration: "10-15 minutes",
      participants: "Bride's family, Groom",
      offerings: "Sugar, cloth, gifts",
      bestTime: "Pre-wedding ceremony",
      videos: "Marathi Sakharpuda Sugar Ritual",
    },
  },
  "Manipur": {
    "Betel Leaf Exchange": {
      description: "Bride and groom exchange betel leaves as sacred ritual",
      history: "Ancient Manipuri tradition with spiritual significance.",
      significance: "Represents acceptance, binding agreement, and marital union.",
      process: [
        "Fresh betel leaves prepared",
        "Groom offers to bride",
        "Bride accepts and reciprocates",
        "Both consume the leaves",
        "Ceremony completed symbolically",
      ],
      culturalImportance: "Central to Manipuri marriage ceremony.",
      region: "Manipur",
      duration: "10 minutes",
      participants: "Bride, Groom, Witnesses",
      offerings: "Betel leaves, areca nuts",
      bestTime: "During marriage ceremony",
      videos: "Manipuri Betel Leaf Exchange Ritual",
    },
    "Pheijom Dress Ritual": {
      description: "Traditional Manipuri dress wrapping with cultural rules",
      history: "Ancient tradition maintaining dress code and cultural identity.",
      significance: "Preserves cultural heritage and feminine identity.",
      process: [
        "Traditional Pheijom saree is selected",
        "Draped according to traditions",
        "Specific patterns for occasions",
        "Accessories chosen carefully",
        "Worn with respect to traditions",
      ],
      culturalImportance: "Maintains Manipuri cultural identity and dress code.",
      region: "Manipur",
      duration: "20-30 minutes for wearing",
      participants: "Women, elderly advisors",
      offerings: "Traditional Pheijom, jewelry",
      bestTime: "Religious and cultural ceremonies",
      videos: "Pheijom Dress Wearing Manipur Ritual",
    },
  },
  "Meghalaya": {
    "Matrilineal Inheritance": {
      description: "Property inherited through women, unique matrilineal system",
      history: "Ancient Khasi tradition maintaining matrilineal lineage and property rights.",
      significance: "Empowers women, maintains female economic independence.",
      process: [
        "Youngest daughter inherits ancestral home",
        "Property management by women",
        "Sons inherit through their wives",
        "Ensures women's security",
        "Maintains family stability",
      ],
      culturalImportance: "Unique to Meghalaya, pre-dates modern women's rights movements.",
      region: "Meghalaya - Khasi communities",
      duration: "Throughout life",
      participants: "Family members, community elders",
      offerings: "Property, resources, family management",
      bestTime: "After marriage and inheritance",
      videos: "Meghalaya Matrilineal System Khasi Culture",
    },
    "Khasi Shawl Reception": {
      description: "Receiving Khasi shawl as symbol of honor",
      history: "Traditional custom honoring achievements and status.",
      significance: "Public recognition of status and respect.",
      process: [
        "Khasi shawl presented formally",
        "Wrapped around recipient",
        "Community witnesses honor",
        "Celebration follows",
        "Symbol of accomplishment",
      ],
      culturalImportance: "Maintains honor system and public recognition.",
      region: "Meghalaya",
      duration: "Ceremonial event",
      participants: "Community members, recipient, elders",
      offerings: "Khasi shawl, gifts",
      bestTime: "Special occasions and ceremonies",
      videos: "Khasi Shawl Honor Ceremony Meghalaya",
    },
  },
  "Mizoram": {
    "Cheraw Dance": {
      description: "Traditional bamboo stick dance performed at weddings",
      history: "Ancient Mizo tradition celebrating joy and community.",
      significance: "Brings blessings and joyful energy to celebrations.",
      process: [
        "Bamboo sticks arranged on ground",
        "Dancers step in rhythmic patterns",
        "Complex movements require skill",
        "Community participates",
        "Joyful celebration and music",
      ],
      culturalImportance: "National dance of Mizoram, symbol of cultural pride.",
      region: "Mizoram",
      duration: "1-2 hours of performance",
      participants: "Dancers, musicians, community",
      offerings: "Traditional costumes, music",
      bestTime: "Weddings, festivals, celebrations",
      videos: "Cheraw Dance Mizoram Wedding Ceremony",
    },
    "Zu Welcome Ritual": {
      description: "Welcoming guests with traditional rice drink",
      history: "Ancient Mizo hospitality tradition.",
      significance: "Shows respect and welcome to guests.",
      process: [
        "Rice fermented for traditional zu",
        "Served in traditional vessel",
        "Guest offered first",
        "Shared communally",
        "Sign of acceptance",
      ],
      culturalImportance: "Maintains hospitality customs and community bonding.",
      region: "Mizoram",
      duration: "Part of welcome ceremony",
      participants: "Host and guests",
      offerings: "Zu (rice drink), traditional foods",
      bestTime: "Guest arrival and celebration",
      videos: "Mizo Zu Drink Welcome Ritual",
    },
  },
  "Nagaland": {
    "Morung System": {
      description: "Tribal education center for training youth in traditions",
      history: "Ancient Naga institution for cultural and physical training.",
      significance: "Preserves tribal knowledge and prepares youth for adulthood.",
      process: [
        "Young people join Morung",
        "Traditional skills taught",
        "Community defense training",
        "Cultural education provided",
        "Preparation for marriage",
      ],
      culturalImportance: "Central to Naga society, maintains cultural continuity.",
      region: "Nagaland tribal communities",
      duration: "Several years",
      participants: "Youth, elders, tribal leaders",
      offerings: "Training, mentorship, community support",
      bestTime: "Youth coming of age period",
      videos: "Nagaland Morung Tribal Youth Training",
    },
    "Hornbill Feather Ritual": {
      description: "Wearing hornbill feathers indicating status and achievement",
      history: "Ancient Naga tradition honoring warrior status and achievement.",
      significance: "Symbol of valor, courage, and high social standing.",
      process: [
        "Hornbill feathers collected",
        "Worn during ceremonies",
        "Indicates social rank",
        "Public recognition of status",
        "Inheritance of feathers possible",
      ],
      culturalImportance: "Maintains status system and tribal hierarchy.",
      region: "Nagaland",
      duration: "Throughout ceremonial occasions",
      participants: "Warriors, leaders, community",
      offerings: "Hornbill feathers, traditional attire",
      bestTime: "Festivals, war commemorations, ceremonies",
      videos: "Nagaland Hornbill Feather Warrior Ritual",
    },
  },
  "Odisha": {
    "Jugalbandhi Ritual": {
      description: "Joining bride and groom's hands with coconut",
      history: "Traditional Odiya wedding ritual with ancient roots.",
      significance: "Symbolizes binding union and life partnership.",
      process: [
        "Bride and groom hands joined",
        "Coconut held between hands",
        "Priest performs mantras",
        "Family blesses couple",
        "Coconut distributed",
      ],
      culturalImportance: "Core ritual in Odiya weddings, ensures spiritual union.",
      region: "Odisha",
      duration: "15-20 minutes",
      participants: "Bride, Groom, Priest, Family",
      offerings: "Coconut, flowers, sacred materials",
      bestTime: "During wedding ceremony",
      videos: "Odiya Jugalbandhi Wedding Ritual",
    },
    "Saura Wall Painting": {
      description: "Tribal wall paintings before auspicious events",
      history: "Ancient Saura tribal art tradition for spiritual protection.",
      significance: "Invokes divine blessings and protection for events.",
      process: [
        "Walls prepared with natural clay",
        "Intricate patterns drawn",
        "Natural colors used",
        "Specific designs for occasions",
        "Community participation",
      ],
      culturalImportance: "Preserves tribal art form, maintains spiritual connection.",
      region: "Odisha tribal areas",
      duration: "Several hours to full day",
      participants: "Tribal women, family members",
      offerings: "Natural materials, clay, colors",
      bestTime: "Before weddings and festivals",
      videos: "Saura Tribal Wall Painting Odisha",
    },
  },
  "Punjab": {
    "Mehndi Ceremony": {
      description: "Application of henna on bride's hands and feet",
      history: "Ancient tradition dating back to medieval period.",
      significance: "Celebrates bride, represents love and joy.",
      process: [
        "Professional mehndi artist applies designs",
        "Groom's initials hidden in design",
        "Family celebration with music",
        "Takes 4-6 hours for completion",
        "Darker color indicates strong love",
      ],
      culturalImportance: "Essential to Punjabi wedding celebrations.",
      region: "Punjab, North India",
      duration: "4-6 hours",
      participants: "Bride, family, female friends",
      offerings: "Henna, oils, sweets, jewelry gifts",
      bestTime: "2-3 days before wedding",
      videos: "Punjabi Mehndi Ceremony Wedding",
    },
    "Baraat Procession": {
      description: "Groom's ceremonial procession to bride's venue",
      history: "Ancient Vedic tradition symbolizing groom's confidence.",
      significance: "Displays family pride, marks wedding beginning.",
      process: [
        "Groom rides horse with decorated saddle",
        "Family and friends accompany",
        "Dhol music and dancing",
        "Bride's family receives with honors",
        "Joyful celebration",
      ],
      culturalImportance: "Iconic element of Punjabi weddings.",
      region: "Punjab, North India",
      duration: "2-3 hours",
      participants: "Groom, family, musicians, dancers",
      offerings: "Flowers, sweets, gifts",
      bestTime: "Evening before or morning of wedding",
      videos: "Punjabi Baraat Traditional Ceremony",
    },
  },
  "Rajasthan": {
    "Pagdi Tying": {
      description: "Ceremonial tying of turban symbolizing honor",
      history: "Ancient Rajasthani tradition honoring warriors and leaders.",
      significance: "Symbol of respect, honor, and social status.",
      process: [
        "Special cloth selected for pagdi",
        "Tied by honored family member",
        "Formal ceremony performed",
        "Community witnesses",
        "Celebration follows",
      ],
      culturalImportance: "Maintains honor system in Rajasthan.",
      region: "Rajasthan",
      duration: "30 minutes to 1 hour ceremony",
      participants: "Honoree, family members, community",
      offerings: "Special pagdi cloth, gifts",
      bestTime: "Coming of age, weddings, honors",
      videos: "Rajasthan Pagdi Tying Honor Ceremony",
    },
    "Phera Dhalna": {
      description: "Couple visits seven courtyards in marriage ritual",
      history: "Traditional Rajasthani marriage ceremony component.",
      significance: "Represents couple's journey through married life.",
      process: [
        "Bride and groom proceed together",
        "Visit each of seven courtyards",
        "Blessings received at each",
        "Fire rituals at some locations",
        "Community participation",
      ],
      culturalImportance: "Core ritual in Rajasthani weddings.",
      region: "Rajasthan",
      duration: "1-2 hours",
      participants: "Bride, Groom, Family, Priest",
      offerings: "Flowers, sacred materials",
      bestTime: "During wedding ceremony",
      videos: "Rajasthan Phera Dhalna Wedding Ritual",
    },
  },
  "Sikkim": {
    "Butter Lamp Ritual": {
      description: "Buddhist ceremony lighting butter lamps for blessings",
      history: "Ancient Buddhist tradition honoring divine light.",
      significance: "Dispels darkness, brings enlightenment and blessings.",
      process: [
        "Butter lamps (diyas) prepared",
        "Lit with prayers",
        "Placed at altar or sacred space",
        "Mantras chanted",
        "Community gathers",
      ],
      culturalImportance: "Central to Sikkimese Buddhist culture.",
      region: "Sikkim",
      duration: "30 minutes to 1 hour",
      participants: "Family, monks, community",
      offerings: "Butter lamps, incense, prayers",
      bestTime: "Religious ceremonies and festivals",
      videos: "Sikkimese Buddhist Butter Lamp Ritual",
    },
    "Pang Lhabsol Festival": {
      description: "Ritual celebrating mountain goddess Kanyechonma",
      history: "Ancient Sikkimese festival honoring protective deity.",
      significance: "Ensures protection and prosperity for land.",
      process: [
        "Community gathers on set date",
        "Traditional dance performed",
        "Prayers offered to goddess",
        "Traditional dress worn",
        "Celebration with music",
      ],
      culturalImportance: "Important Sikkimese cultural festival.",
      region: "Sikkim",
      duration: "Full day celebration",
      participants: "Entire community, monks",
      offerings: "Flowers, prayers, traditional foods",
      bestTime: "Autumn month (September)",
      videos: "Pang Lhabsol Mountain Goddess Festival Sikkim",
    },
  },
  "Tamil Nadu": {
    "Vidyarambham": {
      description: "First writing ceremony for children beginning education",
      history: "Ancient Tamil tradition initiating formal education.",
      significance: "Seeks blessing for intellectual development.",
      process: [
        "Child brought to temple",
        "Priest guides first writing",
        "Rice grains form letters",
        "Prayers recited",
        "Celebration with family",
      ],
      culturalImportance: "Maintains Tamil educational traditions.",
      region: "Tamil Nadu",
      duration: "1-2 hours",
      participants: "Child, parents, priest",
      offerings: "Flowers, rice, fruits, gifts",
      bestTime: "Age 2-3 years or auspicious date",
      videos: "Vidyarambham Tamil Child Education Ritual",
    },
    "Mangalsutra Ritual": {
      description: "Tying sacred necklace with three sacred knots",
      history: "Ancient Tamil marriage tradition with deep symbolism.",
      significance: "Represents marital bond and husband's commitment.",
      process: [
        "Mangalsutra is blessed",
        "Groom ties around bride's neck",
        "Three sacred knots tied",
        "Family blesses couple",
        "Completion of union",
      ],
      culturalImportance: "Most important symbol of married woman status.",
      region: "Tamil Nadu, South India",
      duration: "15-20 minutes",
      participants: "Bride, Groom, Priest, Family",
      offerings: "Mangalsutra, flowers",
      bestTime: "During wedding ceremony",
      videos: "Tamil Mangalsutra Marriage Ritual",
    },
  },
  "Telangana": {
    "Mangala Harathi": {
      description: "Turmeric-water blessing ritual before ceremonies",
      history: "Ancient Telangana tradition for purification.",
      significance: "Purifies and invokes divine blessings.",
      process: [
        "Water mixed with turmeric",
        "Offered to main person",
        "Applied to face and head",
        "Prayers recited",
        "Spiritual cleansing",
      ],
      culturalImportance: "Common pre-ceremony ritual in Telangana.",
      region: "Telangana",
      duration: "10-15 minutes",
      participants: "All participants in ceremony",
      offerings: "Water, turmeric, flowers",
      bestTime: "Before important ceremonies",
      videos: "Telangana Mangala Harathi Blessing Ritual",
    },
    "Bonalu Ritual": {
      description: "Pot offering to goddess for purification",
      history: "Ancient tribal ritual honoring mother goddess.",
      significance: "Seeks protection and prosperity for family.",
      process: [
        "Earthen pots prepared",
        "Filled with rice, jaggery, clothes",
        "Offered to goddess",
        "Community participation",
        "Procession and celebration",
      ],
      culturalImportance: "Unique Telangana summer festival ritual.",
      region: "Telangana",
      duration: "2-3 hours",
      participants: "Women, family members, community",
      offerings: "Earthen pots, rice, jaggery, flowers",
      bestTime: "Summer months (May-June)",
      videos: "Bonalu Festival Goddess Ritual Telangana",
    },
  },
  "Tripura": {
    "Garia Ritual": {
      description: "Daily prosperity ritual for household welfare",
      history: "Ancient Tripura belief system for continuous blessings.",
      significance: "Ensures ongoing prosperity and family well-being.",
      process: [
        "Daily prayers and offerings",
        "Specific items offered",
        "Mantras recited",
        "Family participation",
        "Year-round practice",
      ],
      culturalImportance: "Maintains daily spiritual connection.",
      region: "Tripura",
      duration: "15-20 minutes daily",
      participants: "Family members",
      offerings: "Flowers, grains, traditional items",
      bestTime: "Daily, especially morning",
      videos: "Garia Daily Prosperity Ritual Tripura",
    },
    "House Blessing Ritual": {
      description: "Blessing new or existing home with sacred bamboo",
      history: "Traditional tribal custom for home protection.",
      significance: "Seeks divine protection for residents.",
      process: [
        "Sacred bamboo collected",
        "Placed at entrance",
        "Prayers and rituals performed",
        "Holy water sprinkled",
        "Community witnesses",
      ],
      culturalImportance: "Ensures family safety and prosperity.",
      region: "Tripura",
      duration: "1-2 hours",
      participants: "Family, tribal priest, neighbors",
      offerings: "Sacred bamboo, flowers, rice",
      bestTime: "Before entering new home",
      videos: "House Blessing Bamboo Ritual Tripura",
    },
  },
  "Uttar Pradesh": {
    "Ganga Jal Ritual": {
      description: "Purification with holy Ganges water before ceremonies",
      history: "Ancient Hindu tradition honoring sacred river.",
      significance: "Ultimate spiritual purification in Hindu custom.",
      process: [
        "Holy Ganges water collected",
        "Applied to foreheads",
        "Consumed in small quantity",
        "Prayers offered",
        "Spiritual purification achieved",
      ],
      culturalImportance: "Most sacred ritual in Hindu tradition.",
      region: "Uttar Pradesh, across North India",
      duration: "15-30 minutes",
      participants: "All ceremony participants",
      offerings: "Ganges water, flowers",
      bestTime: "Before major ceremonies",
      videos: "Ganga Jal Purification Ritual UP",
    },
    "Pehli Rasoi": {
      description: "Bride's first meal cooked in new home",
      history: "Traditional ritual symbolizing bride's entry into household duties.",
      significance: "Marks bride's formal entry as family member.",
      process: [
        "Bride prepares simple meal",
        "Family gathers for meal",
        "Special blessing given",
        "Celebrated with joy",
        "Marks new chapter",
      ],
      culturalImportance: "Important ritual in North Indian weddings.",
      region: "Uttar Pradesh, North India",
      duration: "1-2 hours",
      participants: "Bride, Groom, Groom's family",
      offerings: "Food items, flowers, gifts",
      bestTime: "First day in new home",
      videos: "Pehli Rasoi Bride First Cooking UP",
    },
  },
  "Uttarakhand": {
    "Jagar Ritual": {
      description: "Singing folk songs to call ancestral spirits",
      history: "Ancient mountain tradition connecting with ancestors.",
      significance: "Seeks guidance and blessings from ancestors.",
      process: [
        "Folk singers gather",
        "Traditional songs sung",
        "Incense and offerings made",
        "Throughout night",
        "Community participates",
      ],
      culturalImportance: "Maintains ancestral connection and folk culture.",
      region: "Uttarakhand mountains",
      duration: "Several hours to full night",
      participants: "Family, singers, community",
      offerings: "Incense, flowers, traditional foods",
      bestTime: "Special occasions, grief ceremonies",
      videos: "Jagar Ritual Uttarakhand Ancestral Connection",
    },
    "Kul Devta Worship": {
      description: "Worshipping family deity before major decisions",
      history: "Ancient mountain tradition honoring protective family god.",
      significance: "Seeks blessing and guidance for life decisions.",
      process: [
        "Family gathers at shrine",
        "Prayers to Kul Devta",
        "Offerings made",
        "Seeking divine guidance",
        "Decision made with blessings",
      ],
      culturalImportance: "Guides important family decisions.",
      region: "Uttarakhand mountain communities",
      duration: "1-2 hours",
      participants: "Family members, priest",
      offerings: "Flowers, fruits, sweets, incense",
      bestTime: "Before marriages, travels, ventures",
      videos: "Kul Devta Family Deity Worship Uttarakhand",
    },
  },
  "West Bengal": {
    "Betel Leaf Wedding": {
      description: "Bride's face covered with betel leaves during ceremony",
      history: "Ancient Bengali wedding tradition adding charm.",
      significance: "Represents bride's modesty and mystery.",
      process: [
        "Fresh betel leaves arranged",
        "Cover bride's face",
        "Groom playfully removes leaves",
        "Traditional songs sung",
        "Romantic moment created",
      ],
      culturalImportance: "Unique to Bengali weddings.",
      region: "West Bengal",
      duration: "10-15 minutes",
      participants: "Bride, Groom, Family",
      offerings: "Fresh betel leaves, flowers",
      bestTime: "During wedding ceremony",
      videos: "Bengali Wedding Betel Leaf Ritual",
    },
    "Durga Puja": {
      description: "Grand ten-day festival celebrating goddess Durga",
      history: "Documented for 400+ years, most important Bengali festival.",
      significance: "Victory of good over evil, celebrates feminine power.",
      process: [
        "Elaborate pandals constructed",
        "Idols crafted with artistic skill",
        "Daily rituals performed",
        "Community feasts held",
        "Cultural programs organized",
      ],
      culturalImportance: "UNESCO-recognized, defines Bengali cultural identity.",
      region: "West Bengal, Bengali communities worldwide",
      duration: "10 days during Ashwin month",
      participants: "Entire community",
      offerings: "Flowers, incense, prasad, animal sacrifice",
      bestTime: "September-October (Ashwin month)",
      videos: "Durga Puja West Bengal Grand Festival",
    },
  },
};
