/**
 * Pre-fetched Pexels Images Database
 * This file is auto-generated by running: node fetch_all_city_images.js
 * 
 * DO NOT EDIT MANUALLY - Run the fetch script to update images
 * 
 * Structure: { cityName: [{ url, thumbnail, photographer }, ...] }
 */

// Import the JSON directly - Vite handles JSON imports natively
import pexelsData from '../data/pexels_images.json';

// Normalize city names for lookup (handles "Cape Town" vs "CapeTown")
const normalizeCity = (city) => {
    if (!city) return '';
    return city
        .toLowerCase()
        .replace(/\s+/g, '') // Remove spaces
        .replace(/-/g, '');  // Remove hyphens
};

// Build a normalized lookup map
const cityImageMap = {};
Object.entries(pexelsData).forEach(([city, images]) => {
    const normalizedKey = normalizeCity(city);
    cityImageMap[normalizedKey] = images;
});

/**
 * Get images for a city from the pre-fetched cache
 * @param {string} cityName - City name (e.g., "Paris", "Cape Town", "Bangkok")
 * @returns {Array} Array of image objects with url, thumbnail, photographer
 */
export const getCityImages = (cityName) => {
    const normalizedKey = normalizeCity(cityName);
    
    // Direct match
    if (cityImageMap[normalizedKey]) {
        return cityImageMap[normalizedKey];
    }
    
    // Fallback: check if it's a suburb of Paris
    const parisFallbacks = ['pantin', 'montreuil', 'bobigny', 'ivrysurseine', 'annecy'];
    if (parisFallbacks.includes(normalizedKey)) {
        // Try to find specific city first, otherwise use Paris
        return cityImageMap[normalizedKey] || cityImageMap['paris'] || [];
    }
    
    // If no match, return Paris images as default (most common)
    return cityImageMap['paris'] || [];
};

/**
 * Get a specific number of images for a city
 * @param {string} cityName - City name
 * @param {number} count - Number of images to return
 * @param {number} offset - Starting offset for variety
 * @returns {Array} Array of image objects
 */
export const getCityImagesSlice = (cityName, count = 10, offset = 0) => {
    const images = getCityImages(cityName);
    if (images.length === 0) return [];
    
    const result = [];
    for (let i = 0; i < count; i++) {
        const idx = (offset + i) % images.length;
        result.push(images[idx]);
    }
    return result;
};

export default pexelsData;
